<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Xeno.ToolsHub.SampleAssmAddin</RootNamespace>
    <AssemblyName>SampleAssmAddin</AssemblyName>
    <OutputPath>..\..\output\</OutputPath>
    <CodeAnalysisRuleSet>..\stylecop.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xeno.ToolsHub\Xeno.ToolsHub.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Addins" Version="1.4.1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>
</Project>
