<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Xeno.ToolsHub.SidebarAddin</RootNamespace>
    <AssemblyName>SidebarAddin</AssemblyName>
    <UseWPF>true</UseWPF>
    <OutputPath>..\..\..\output\</OutputPath>
    <CodeAnalysisRuleSet>..\..\stylecop.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Xeno.ToolsHub\Xeno.ToolsHub.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Addins" Version="1.4.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
  </ItemGroup>
</Project>
